#!/bin/bash
echo Getting items table...
rdmd getter.d ritem
echo Preparing stats...
rdmd prepare.d $@ || exit 1
rdmd prepare.d $@ > curquest.txt
echo Estimating chances...
rdmd curquest.d < curquest.txt > stats.txt
echo Done.
