#!/bin/bash
echo Getting items table...
rdmd getter.d ritem
echo Preparing stats...
rdmd prepare.d $@ | tee curquest.txt
echo Estimating chances...
rdmd curquest.d < curquest.txt > stats.txt
echo Done.
