#!/bin/bash
echo Getting tables...
rdmd getter.d cquest ritem
echo Extracting latest quest information...
rdmd list.d | tee curquest.txt
echo Estimating quest chances...
rdmd curquest.d < curquest.txt > stats.txt
echo Done.
